### L3 Analysis 2-D data using Pandas and Numpy

Two dimensional Data

Python: List of lists<br>
Numpy: 2D array<br>
Pandas: Data Frame. **I preffer this!**

In [29]:
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

# Change False to True for each block of code to see what it does

# Accessing elements
if True:
    print ridership[1, 3]
    print ridership[1:3, 3:5]
    print ridership[1, :]
    print "\n"
# Vectorized operations on rows or columns
if True:
    print ridership[0, :] + ridership[1, :]
    print ridership[:, 0] + ridership[:, 1]
    print "\n"
# Vectorized operations on entire arrays
if True:
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print a + b



2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [20]:
ridership = np.array([[ 5, 10, 15, 20, 25],
       [ 5, 10, 15, 20, 25],
       [ 5, 10, 15, 20, 25]])

Choose the $1^{st}$ row

In [34]:
ridership[0,:]

array([0, 0, 2, 5, 0])

Find the position for the maxium in the first row using argmax()

In [22]:
ridership[0,:].argmax()

4

In [23]:
ridership[:,ridership[0,:].argmax()].max()

25

In [24]:
ridership.max()

25

In [26]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    
    overall_mean = ridership.mean() 
    mean_for_max = ridership[:,ridership[0,:].argmax()].mean() 
    
    return (overall_mean, mean_for_max)

In [30]:
print mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)


In [32]:
ridership.mean(axis = 0)

array([ 1071.2,  2814.9,  2718.8,  3239.9,  1868.2])

In [33]:
ridership.mean(axis = 1)

array([  1.40000000e+00,   2.77920000e+03,   3.76880000e+03,
         3.23560000e+03,   3.50480000e+03,   3.41640000e+03,
         2.55200000e+02,   6.00000000e+00,   3.04020000e+03,
         3.41840000e+03])

In [39]:
print (ridership.mean(axis =0)).max()
(ridership.mean(axis =0)).min()

3239.9


1071.2